export const experiences = [
  {
    title: "Software Engineer 2",
    dates: "Dec 2021 - Feb 2024",
    company: "Bluebeam Inc.",
    location: "Remote",
    duties: [
      "Led front end development for one of Bluebeam’s Cloud Initiative agile teams, setting development direction and goals, while building reusable JavaScript components from Figma prototype designs using React/Typescript, Tailwind CSS, Redux, Flexbox and Grid",
      "Worked collaboratively with other frontend and backend teams to integrate UI features and components with their work to help drive subscription rates.",
      "Led efforts to refactor and optimize existing UI elements, driven by customer feedback and usage metrics while maintaining in house design standards and styles.",
      "Built layouts and reusable components using Typescript, React, Next.js, Flexbox, Grid, CSS with accessibility, user interactions and frontend best practices in mind.",
      "Provided mentorship and close guidance to interns, fostering their growth and development as JavaScript, HTML and CSS developers.",
      "Deployed code to testing and production environments using CI/CD pipelines and AWS CloudWatch tools.",
    ],
  },
  {
    title: "Software Engineer",
    dates: "Oct 2018 - Oct 2021",
    company: "Jigsaw XYZ, Inc.",
    location: "New York, NY",
    duties: [
      "Part of an agile team that used React/Typescript and Node to develop and launch the LookSee property solutions app for Standard Bank South Africa at https://www.looksee.co.za/. worked closely with the client to achieve success.",
      "Worked on several fast-paced proof of concept projects helping win contracts for financial and banking clients including NCR, Motive Partners, and Standard Bank.",
      "Converted designs from Figma / Sketch into fully functional UI using Flexbox, Grid, React, React Native, Redux, Typescript, JavaScript HTML and CSS",
      "Learned React fundamentals and best practices such as context, prop usage, state management, and reusable component design.",
      "Used Git repositories and NPM to both install and host libraries.",
      "Honed a deep understanding of frontend UI best practices including layouts, smooth user interactions, and accessibility.",
      "Containerized projects using Docker and deployed / monitored apps with Azure.",
      "Helped design, implement, and retrieve data for UIs from backend RESTful APIs.",
    ],
  },
];

export const projects = [
  {
    title: "StefCo. Store",
    link: "https://github.com/stefegg/stef-co-store",
    description: "",
    techStack: [
      "React",
      "Typescript",
      "Tailwind CSS",
      "Next.js",
      "Vercel",
      "Prisma",
      "PostgreSQL",
    ],
  },
  {
    title: "Bluebeam Cloud",
    link: "https://app.bluebeam.com",
    description: "",
    techStack: [
      "React",
      "Typescript",
      "Tailwind CSS",
      "Styled-Components",
      "Sass",
      "Jest",
      "Storybook",
      "AG Grid",
    ],
  },
  {
    title: "LookSee",
    link: "https://www.looksee.co.za",
    description: "",
    techStack: ["React", "Typescript", "Styled-Components", "Storybook"],
  },
  {
    title: "WeatherApp",
    link: "https://github.com/stefegg/weatherapp",
    description: "",
    techStack: ["React Native", "Expo", "CSS"],
  },
  {
    title: "Calendar App",
    link: "https://github.com/stefegg/calendar-app",
    description: "",
    techStack: ["React", "Styled-Components", "Typescript"],
  },
  {
    title: "Learnwell Video Suite",
    link: "https://github.com/stefegg/learnwell-vids",
    description: "",
    techStack: ["React", "Typescript", "Tailwind CSS"],
  },
  {
    title: "Stripe Hotel",
    link: "https://github.com/stefegg/stripe-hotel",
    description: "",
    techStack: [
      "React",
      "Recoil",
      "Node.js",
      "Express",
      "Storybook",
      "Styled-Components",
    ],
  },
  {
    title: "VFZ",
    link: "https://github.com/stefegg/vfz",
    description: "",
    techStack: ["Javascript", "HTML"],
  },
  {
    title: "Persephone",
    link: "https://github.com/stefegg/persephone",
    description: "",
    techStack: ["Javascript", "Ruby", "Rails", "HTML", "CSS"],
  },
  {
    title: "Postboy Driving",
    link: "https://github.com/stefegg/postboy-driving-school",
    description: "",
    techStack: ["Javascript", "Ruby", "Rails", "HTML", "CSS"],
  },
  {
    title: "Personal Pokedex",
    link: "https://stefegg.github.io/pokedex/",
    description: "",
    techStack: ["Javascript", "HTML", "CSS"],
  },
];
